In [98]:
import numpy as np
import pandas as pd
import yaml
import matplotlib.pyplot as plt
from scipy.io import loadmat
from util.dataset_util import get_start_end_indeces
#get the first ans las observations done in this time period

def get_list_of_observations(data, start_time, end_time):

	start_time_index = np.where(data[:,0] >= start_time) # get the index of the starting time
	end_time_index = np.where(data[:,0] <= end_time)
	indices = np.intersect1d(start_time_index,end_time_index)

	# print(indices)
	# print("Times are",data[indices,0])
	return data[indices] 


# from util.dataset_util import get_list_of_observations



Robot = 2
np.random.seed(1)

### import parameters
with open('config.yaml') as config_file:
	config = yaml.load(config_file, Loader=yaml.FullLoader)


landmark_ids = [72,27,54,70,36,18,25,9,81,16,90,61,45,7,63]
landmarks_list = {
    72:[5.70928255,4.964045],
    27:[5.2529261, 5.53656921],
    54:[3.69987701,4.46642332],
    70:[2.31446307,3.374987],
    36:[0.48179893,4.3959718],
    18:[3.15072,2.38294871],
    25:[4.06328771,0.94429372],
    9:[2.68034388,0.26835185],
    81:[0.94828519,0.75601306],
    16:[3.76290153,-2.03091517],
    90:[1.6983677,-2.08966931],
    61:[0.03596156,-2.84396626],
    45:[0.94291375,-5.43445742],
    7:[2.5901702,-5.52265035],
    63:[2.09939861,-3.91527208]}


if Robot == 1:
	#Load the sampled data by Matlab
	R1_gt = loadmat('Sampled_dataset/Robot1_Groundtruth.mat')['Robot1_Groundtruth']
	R1_obs = loadmat('Sampled_dataset/Robot1_Measurement.mat')['Robot1_Measurement']
	R1_odom = loadmat('Sampled_dataset/Robot1_Odometry.mat')['Robot1_Odometry']

elif Robot == 2:
	#Load the sampled data by Matlab
	R1_gt = loadmat('Sampled_dataset/Robot2_Groundtruth.mat')['Robot2_Groundtruth']
	R1_obs = loadmat('Sampled_dataset/Robot2_Measurement.mat')['Robot2_Measurement']
	R1_odom = loadmat('Sampled_dataset/Robot2_Odometry.mat')['Robot2_Odometry']

elif Robot == 3:
	#Load the sampled data by Matlab
	R1_gt = loadmat('Sampled_dataset/Robot3_Groundtruth.mat')['Robot3_Groundtruth']
	R1_obs = loadmat('Sampled_dataset/Robot3_Measurement.mat')['Robot3_Measurement']
	R1_odom = loadmat('Sampled_dataset/Robot3_Odometry.mat')['Robot3_Odometry']


percision = 3
# print(R1_gt.shape)
# print(R1_obs.shape)
# print(R1_odom.shape)
#Round the time
R1_gt[:,0] = np.round(R1_gt[:,0],percision)
R1_odom[:,0] = np.round(R1_odom[:,0],percision)
R1_obs[:,0] = np.round(R1_obs[:,0],percision)

idx = 0
obs_idx = 0
start_time = 0
# start_time = 1000 #seconds
duration = 2099
end_time = start_time + duration
start_idx, end_idx = get_start_end_indeces(R1_gt, start_time, end_time)


sample_time = config['dt'] # 0.02


print("gt start and end times :", R1_gt[start_idx,0],R1_gt[end_idx,0])
print("odom start and end time :", R1_odom[start_idx,0], R1_odom[end_idx,0])

observations = get_list_of_observations(R1_obs, start_time, end_time)
print(len(observations))
#print(observations)
print("Start")
for i in range(start_idx, end_idx, 1):
    t = R1_odom[i,0]
    observed_landmark_index = np.where(observations[:,0]==t)[0]
    #print(observed_landmark_index)
    if (len(observed_landmark_index)): #if a landmark index exists
        for j in observed_landmark_index:
            #print(observations[j][0])
            obs_idx = obs_idx + 1

print(obs_idx)






gt start and end times : 0.0 2099.0
odom start and end time : 0.0 2099.0
9073
Start
9073


In [36]:
[[1728.      61.       2.104    0.491]
 [1728.64    70.       1.922   -0.507]
 [1728.86    70.       2.023   -0.35 ]
 [1729.08    70.       2.006   -0.349]
 [1729.28    70.       1.973   -0.344]
 [1729.5     70.       1.937   -0.36 ]
 [1729.74    70.       1.894   -0.367]
 [1729.96    70.       1.856   -0.375]
 [1730.18    70.       1.819   -0.384]
 [1730.4     70.       1.782   -0.388]
 [1730.62    70.       1.758   -0.389]
 [1730.84    70.       1.731   -0.396]
 [1731.04    70.       1.758   -0.293]
 [1731.26    70.       1.771   -0.177]
 [1731.46    70.       1.781   -0.059]
 [1731.68    70.       1.747    0.063]
 [1731.9     70.       1.716    0.087]
 [1732.12    70.       1.695    0.087]
 [1732.34    70.       1.659    0.095]
 [1732.56    70.       1.606    0.097]
 [1732.78    70.       1.586    0.094]
 [1733.      70.       1.548    0.097]]

[0 1 2 3 4]
